/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Executable */

#ifndef _Included_Executable
#define _Included_Executable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Executable
 * Method:    initBinary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Executable_initBinary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Executable
 * Method:    saveAt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Executable_saveAt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Executable
 * Method:    findSection
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Executable_findSection__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Executable
 * Method:    findSection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Executable_findSection__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     Executable
 * Method:    findFunction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Executable_findFunction__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Executable
 * Method:    findFunction
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Executable_findFunction__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
