/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Function */

#ifndef _Included_Function
#define _Included_Function
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Function
 * Method:    findInstruction
 * Signature: (I)LInstruction;
 */
JNIEXPORT jobject JNICALL Java_Function_findInstruction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
